#!/bin/sh

EXEC=$(realpath $0)
EXEC_DIR=$(dirname $EXEC)

NODE_WEBKIT_PATH=nwjs/linux-x64
export LD_LIBRARY_PATH=$NODE_WEBKIT_PATH:$LD_LIBRARY_PATH

if [ "$1" != "" ]; then
  file=$(realpath $1)
  cd $EXEC_DIR && exec $NODE_WEBKIT_PATH/nw app "$file"
else
  cd $EXEC_DIR && exec $NODE_WEBKIT_PATH/nw app
fi
